---
title: "pakkesetup"
output: html_document
date: '2022-05-22'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#funktioner til at bygge pakke

devtools::create("RyouSick") #Husk at tilføje dependencies i import (pipe operatoren), og lav :: notation når funktioner fra andre pakker bruges i koden

usethis::use_package_doc() #docs til ?package_name 
usethis::use_mit_license() #licens
usethis::use_readme_md() #Frontside/github tekst   
usethis::use_pipe()
usethis::use_github_action_check_standard()

devtools::document() #konverterer dokumentationer og tilføjer namespaces
usethis::use_vignette("Simulation_Basis") #Laver vignettes/artikler. Lav en med samme navn som pakken for at få "get started" siden. 


```

```{r}
#installation af pakke fra samme mappe 
devtools::load_all()
devtools::install()
#installation af pakke fra github
devtools::install_github("Best-Nicklas/TestPackageSiteR")
```

```{r}
#funktioner til at bygge hjemmeside
usethis::use_pkgdown() #laver yaml fil
pkgdown::build_site() #Bygger siden lokalt
usethis::use_pkgdown_github_pages() #forbinder til github pages 
devtools::check()

```



